common/urls.py
from django.contrib.auth import views as auth_views
from common.views import (
    HomePage, account_activation_sent, activate, SignUpView, ProfileView,
    ForgotPasswordView, load_districts, load_counties,load_sub_counties,
    load_parishes,load_villages, activate,ChangePasswordView,account_activated
)

from django.urls import path,include
from rest_framework import routers
from . import views



router = routers.DefaultRouter()

router.register(r'register', views.UserViewSet,'users')
router.register(r'groups', views.GroupViewSet,'groups')
router.register(r'counties',views.CountyViewSet,'counties')
router.register(r'sub_counties',views.SubCountyViewSet,'sub_counties')
router.register(r'districts', views.DistrictViewSet,'districts')
router.register(r'parishes',views.ParishViewSet,'parishes')
router.register(r'villages',views.VillageViewSet, 'villages')
router.register(r'post_users', views.PostUserDataViewSet, 'post_users')
router.register(r'profiles', views.PostProfileViewSet, 'profiles')
router.register(r'regions',views.RegionViewSet, 'regions')


app_name ='common'

urlpatterns = [
    path('api/', include(router.urls)),
    path('', HomePage.as_view(), name='home'),
    path('account/change_password', ChangePasswordView.as_view(), name='change_password'),
    path('account_activation_sent/', account_activation_sent, name='account_activation_sent'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('account/activated', account_activated, name='activated'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('<int:pk>/view/profile', ProfileView.as_view(), name="view_profile"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # load districts url
    path('ajax/load-districts/', load_districts, name='ajax_load_districts'),
    path('ajax/load-counties/', load_counties, name='ajax_load_counties'),
    path('ajax/load-sub_counties/', load_sub_counties, name='ajax_load_sub_counties'),
    path('ajax/load-parishes/', load_parishes, name='ajax_load_parishes'),
    path('ajax/load-villages/', load_villages, name='ajax_load_villages'),

   
] 

farm/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import (SectorList, SectorDetail, CreateSector,EnterpriseList, FarmListView, FarmViewSet, 
CreateFarmView, EditFarmView,FarmproductionRecordsList,FarmproductionRecordsList,CreateFarmProductionRecordView,FarmMapViewSet,CreateEnterpriseView,EditEnterpriseView,CreateQueryView,
FarmProfileDetailView,QueryList,CreateFarmRecordView, FarmRecordsList, EditFarmRecordView,
CreateFarmFinancialRecordView,EditFarmproductionRecordView, EditFarmFinancialRecordView, FarmFinancilRecordsList,EditQueryView, EnterpriseSelectionView,
EnterpriseSelectionRedirect,EnterpriseSelectionDetailView)


router = routers.DefaultRouter()

router.register(r'farms', views.FarmViewSet,'farm-api')
router.register(r'maps', views.FarmMapViewSet,'maps-api')
router.register(r'sector', views.SectorViewSet,'apisector')
router.register(r'enterpriseselection', views.EnterpriseSelectionViewSet,'api-enterpriseselection' )
router.register(r'enterprise', views.EnterpriseViewSet, basename='Enterprise')
router.register(r'farmrecords', views.FarmRecordViewSet, basename='FarmRecord')
router.register(r'financialrecords',views.FarmFinancialRecordViewSet,'FinancialRecord')
router.register(r'productionrecords',views.FarmProductionRecordViewSet,'ProductionRecord')
router.register(r'query', views.QueryViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'farm'
urlpatterns = [
    path('api/', include(router.urls)),
    path('list', FarmListView.as_view(), name='farm_list'),
    path('create', CreateFarmView.as_view(), name="create_farm"),
    path('sectors', SectorList.as_view(), name='sector_list'),
    path('<int:pk>/edit/farm', EditFarmView.as_view(), name="edit_farm"),
    path('<int:pk>/edit/sector', SectorDetail.as_view(), name="edit_sector"),
    path('create/sector', CreateSector.as_view(), name="create_sector"),
    path('create/query', CreateQueryView.as_view(), name="create_query"),
    path('<int:pk>/edit/query', EditQueryView.as_view(), name="edit_query"),
    path('queries', QueryList.as_view(), name='query_list'),
    path('enterprises', EnterpriseList.as_view(), name='enterprise_list'),
    path('create/enterprise/<int:farm_pk>', CreateEnterpriseView.as_view(), name="create_enterprise"),
    path('<int:pk>/edit/enterprise', EditEnterpriseView.as_view(), name="edit_enterprise"),
    path('<int:pk>/view/', FarmProfileDetailView.as_view(), name="view_farm_profile"),  
    path('create/record/<int:enterprise_pk>', CreateFarmRecordView.as_view(), name="create_farm_record"), 
    path('farmrecords', FarmRecordsList.as_view(), name='farmrecords') ,
    path('<int:pk>/edit/farmrecord', EditFarmRecordView.as_view(), name="edit_farmrecord"),
    path('create/financilrecord/<int:enterprise_pk>', CreateFarmFinancialRecordView.as_view(), name="create_financial_record"), 
    path('financialrecords', FarmFinancilRecordsList.as_view(), name='financialrecords') ,
    path('<int:pk>/edit/financialrecord', EditFarmFinancialRecordView.as_view(), name="edit_financail_record"),
    path('create/productionrecord/<int:enterprise_pk>', CreateFarmProductionRecordView.as_view(), name="create_production_record"), 
    path('productionrecords', FarmproductionRecordsList.as_view(), name='productionrecords') ,
    path('<int:pk>/edit/productionrecord', EditFarmproductionRecordView.as_view(), name="edit_production_record"),
    path('create/enterpriseselection', EnterpriseSelectionView.as_view(), name='enterprise_selection'),
    path('selectenterprises', EnterpriseSelectionRedirect.as_view(), name='select_enterpise'),
    path('<int:pk>/view/selectenterprise', EnterpriseSelectionDetailView.as_view(), name="view_enterprise_selection"),
    #path('viewselectenterprises', EnterpriseSelectionDetailView.as_view(), name='enterprise_selection_detail'),
]

ict4farmers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from common .views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
from common.views import obtain_auth_token 
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title="ICT4Farmers API Docs")

urlpatterns = [
    path('admin/', admin.site.urls),
    # api documentation
    path('api/docs', schema_view),
    # authentication urls
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # api authentication urls
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    # common urls
    path('', include('common.urls', namespace="common")),

    # open market urls
    path('api-openmarket/', include('openmarket.urls', namespace="api-openmarket")),
    path('openmarket/', include('openmarket.urls', namespace="openmarket")),

    # farm urls
  
    path('farm/', include('farm.urls', namespace="farm")),

    # farmer urls
   
    path('farmer/', include('farmer.urls', namespace="farmer")),

    # unffeagents urls
    path('api-unffeagents/', include('unffeagents.urls', namespace="api-unffeagents")),
    path('unffeagents/', include('unffeagents.urls', namespace="unffeagents")),

    # open weather urls
    path('api-weather/', include('weather.urls', namespace="api-weather")),
    path('weather/', include('weather.urls', namespace="weather")),

    # resorce sharing urls
    path('api-resourcesharing/', include('resourcesharing.urls', namespace="api-resourcesharing")),
    path('resourcesharing/', include('resourcesharing.urls', namespace="resourcesharing")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unffeagents/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import (AgentProfileList, MarketList, MarketPriceList, 
NoticeList,CreateAgentProfile, CreateNoticeView,EditNoticeView, EditAgentProfileView,
CallList,EquiryList,CreateEquiryView,EditEquiryView,UsersList)


router = routers.DefaultRouter()
router.register(r'agentprofile', views.AgentProfileViewSet)
router.register(r'market', views.MarketViewSet)
router.register(r'marketprice', views.MarketPriceViewSet)
router.register(r'notice', views.NoticeViewSet)
router.register(r'call', views.CallerViewSet)
router.register(r'response', views.ResponseViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'unffeagents'

urlpatterns = [
    path('api/', include(router.urls)),
    path('agentprofile', AgentProfileList.as_view(), name='agentprofile_list'),
    path('create/agentprofile', CreateAgentProfile.as_view(), name="create_agentprofile"),
    path('create/enquiry/<slug:session_id>', CreateEquiryView.as_view(), name="create_enquiry"),
    path('<int:pk>/edit/agentprofile', EditAgentProfileView.as_view(), name="edit_agent_profile"),
    path('<int:pk>/edit/enquiry', EditEquiryView.as_view(), name="edit_equiry"),
    path('market', MarketList.as_view(), name='market_list'),
    path('marketprice', MarketPriceList.as_view(), name='marketprice_list'),
    path('alert&notification', NoticeList.as_view(), name='notice_list'),
    path('calls',CallList.as_view(), name='calls'),
    path('enquiries',EquiryList.as_view(), name='enquiries'),
    path('create/alert&notification', CreateNoticeView.as_view(), name='add_notice'),
    path('<int:pk>/edit/alert&notification', EditNoticeView.as_view(), name="edit_notice"),
    path('users', UsersList.as_view(), name="users_list"),

]

common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
import phonenumbers
from phonenumber_field.modelfields import PhoneNumberField
from common.choices import(GENDER_CHOICES)
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
# Create your models here.

class TimeStampedModel(models.Model):
    """
    Abstract model class that includes timestamp fields
    """
    created = models.DateTimeField(
        verbose_name=_('Created'),
        auto_now=True)
    modified = models.DateTimeField(
        verbose_name=_('Modified'),
        auto_now=True)

    # pylint: disable=too-few-public-methods
    class Meta:
        """
        Meta options for TimeStampedModel
        """
        abstract = True


class Region(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class District(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class County(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class SubCounty(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    county = models.ForeignKey(County, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Parish(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    sub_county = models.ForeignKey(SubCounty, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Village(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    parish = models.ForeignKey(Parish, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

#Extending the auth_user table
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone_number = PhoneNumberField(blank=False, null=False)
    phone_2 = PhoneNumberField(_('Phone number 2'), blank=True, null=True)
    home_address = models.TextField(max_length=100, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=15)
    profile_pic = models.ImageField(null=True, blank=True)
     # moved users location to profile to avoid redundancy
    region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True, blank=False)
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True, blank=False)
    county = models.ForeignKey(County, on_delete=models.CASCADE, null=True, blank=False)
    sub_county = models.ForeignKey(SubCounty, on_delete=models.CASCADE, null=True, blank=False)
    parish = models.ForeignKey(Parish, on_delete=models.CASCADE, null=True, blank=False)
    village = models.ForeignKey(Village, on_delete=models.CASCADE, null=True, blank=False)


    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

    def get_full_name(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

common/templates/account_activated.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ICT4Farmers</title>
    <!-- Bootstrap core CSS -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <!-- Custom styling plus plugins -->
    {% compress css %}
    <link href="{% static 'css/site.css' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %}{% endblock %}
  </head>
  <body>
    <div>
      <div class="dark">
        <div class="card-title">
          <center>
            <div class="col-md-4 ">
              <img src="{% static "images/logo_circle.png" %}" width="100%;">
            </div>
            <h3>Your account has been activated.Click the link below to login or login using the mobile applications</h3>
            <h4> <a href="{% url "login" %}">Login</a></h4>
        </center>
        </div>

    </div>
  </div>
  </body>
</html>

common/templates/account_activation_email.html
{% block heading %}
Dear {{ user.first_name }} {{user.last_name}},
{% endblock heading %}
{% block content_body %}


Thank you for creating an account in the ICT4Farmers system
Please click on the link below to confirm your registration, If the link doesn't work, copy it and paste it in your browser

http://{{ domain }}{% url 'common:activate' uidb64=uid token=token %}

If you think, it's not you, then just ignore this email.

Kind Regards,
ICT4Farmers Team
{% endblock content_body %}

common/templates/account_activation_invalid.html
your validation token is invalid!!. Please contact admin

common/templates/account_activation_sent.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ICT4Farmers</title>
    <!-- Bootstrap core CSS -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <!-- Custom styling plus plugins -->
    {% compress css %}
    <link href="{% static 'css/site.css' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %}{% endblock %}
  </head>
  <body>
    <div>
      <div class="dark">
        <div class="card-title">
          <center>
            <div class="col-md-4 ">
              <img src="{% static "images/logo_circle.png" %}" width="100%;">
            </div>
            <h3>Please check your email and follow the instructions to complete the registration</h3>
            <h4>Back to login <a href="{% url "login" %}">Click Here?</a></h4>
        </center>
        </div>

    </div>
  </div>
  </body>
</html>

common/templates/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
{% load crispy_forms_tags %}


            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <div class="page-header-left">
                                <h3>Change Password
                                </h3>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <ol class="breadcrumb float-right">
                                <li class="breadcrumb-item"><a href="{% url 'unffeagents:notice_list' %}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item add-new">Accounts</li>
                                <li class="breadcrumb-item active">Change Password </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container-fluid Ends-->

            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card tab2-card">
                            <div class="card-header">
                                <h5>Change Password</h5>
                         
                            </div>
                            <form method="POST" id="form"  novalidate enctype="multipart/form-data" class="card-body">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.old_password|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.new_password1|as_crispy_field }}
                                    </div> 
                                  
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.new_password2|as_crispy_field }}
                                    </div>
                                   
                                  
                                </div>
                              
                                <div class="float-right">
                                    <input type="submit" value="Change password" class="btn btn-primary">


                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                </div>
            
            <!-- Container-fluid Ends-->
            {% endblock %}
           

<!--select 2-->
<!-- latest jquery-->
{% block javascript %}
<!--select 2-->
<script type="text/javascript">

    $(document).ready(function () {
        $('#id_district').select2();
        $('#id_county').select2();
        $('#id_sub_county').select2();
        $('#id_parish').select2();
        $('#id_village').select2();
        $('#id_target_audience').select2();

    });
  
  
  </script>
{% endblock %}

common/templates/county_dropdown_list_options.html
<option value="">--please select--</option>
{% for county in counties %}
<option value="{{ county.pk }}">{{ county.name }}</option>
{% endfor %}

common/templates/destrict_dropdown_list_options.html
<option value="">--please select--</option>
{% for district in districts %}
<option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %}

common/templates/forgot_password.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="ICT4Farmers is system developed by Eight Technologies to manage small scale farmers.">
        <meta name="author" content="Eight Technologies">
        <link rel="icon" href="/images/dashboard/favicon.png" type="image/x-icon">
        <link rel="shortcut icon" href="/images/dashboard/favicon.png" type="image/x-icon">
        <title>ICT4Farmers</title>
     
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    {% compress css %}
    <!-- Font Awesome-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.css' %}">

    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
       <!-- App css-->
       <link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}">
       {% endcompress %}

    <!-- App css-->
    <style>
        body, html {
          height: 100%;
          margin: 0;
        }
        
        .bg {
          /* The image used */
          background-image:url("/static/images/login_bg.jpg");
        
          /* Full height */
          height: 100%; 
          width: 100%;
          /* Center and scale the image nicely */
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
        }

        .login{
            right: 5%;
            margin-left: 12px;
            position: absolute; 
            bottom:28%;
        }
        
        .login h2 {
            color: #145a32;
        }
        .text-color{
            color:#145a32
        }
        </style>
    </head>
    <body >
        <div class="bg">
            <div class="login">
                <div class="row">
                    <div class="col-md-12">
                <h2>Reset Your Password</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="text-color text-center">Enter Your Email</label>
                                <input type="email" name="email" class="form-control" id="id_email" aria-describedby="emailHelp">
                                <small  class="form-text text-danger">{{form.email.errors}}</small>
                              </div>
                            </div>
                             <div class="">
                                {% if error %}
                                <p class="text-danger">{{ message }}</p>
                                {% endif %}
                             </div>
                             
                             <div class="col-md-6  offset-md-2">
                                <input value="Reset Password" class="btn-primary btn-lg btn-block" type="submit">
        
                              </div>
                              <div class="col-md-12 m-2">
                                  <h5 class="text-color float-right"><a class="text-color" href="{% url 'login' %}">Back To Login</a></h5>
                              </div>
                            

                    </div>
                </form>
            </div>
            </div>
              
            </div>
        </div>
    </body>
    </html>

common/templates/parish_dropdown_list_options.html
<option value="">--please select--</option>
{% for parish in parishes %}
<option value="{{ parish.pk }}">{{ parish.name }}</option>
{% endfor %}

common/templates/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.username }} ICT4Farmers Account,
click the link below:
{{ protocol }}://{{ domain }}{% url 'common:password_reset_confirm' uidb64=uid token=token %}
If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.
Sincerely,
{% endautoescape %}

common/templates/sub_county_dropdown_list_options.html
<option value="">--please select--</option>
{% for sub_county in sub_counties %}
<option value="{{ sub_county.pk }}">{{ sub_county.name }}</option>
{% endfor %}

common/templates/village_dropdown_list_options.html
<option value="">--please select--</option>
{% for village in villages %}
<option value="{{ village.pk }}">{{ village.name }}</option>
{% endfor %}